### **Assignment One Part One: Web Scrapping**

**Name:** Jessica Mawuenam Dellason

**Student Number:** 25215734

This project will be based on [Dublin Rental Property Database](http://mlg.ucd.ie/modules/python/sources/rental/index.html) from the list of [posibile links](http://mlg.ucd.ie/modules/python/sources) to choose from.

In [15]:
# Necessary imports and global variables
import urllib.request
import urllib.error
import bs4
import decimal
import csv

main_link = "http://mlg.ucd.ie/modules/python/sources/rental/index.html"

# This list keep the links of each quarter web page found on the main webpage
q_links = []
# Scrapped data is stored here
listings = []

##### **Reading the main webpage**
The link we have does not give us the information we need to analysis directly.

However it gives his links to the pages that contain the needed data.

This block reads the main [web page](http://mlg.ucd.ie/modules/python/sources/rental/index.html) and gives as the links to all the listings by quarter

In [16]:
try:
    # Opening the link to the main webpage
    response = urllib.request.urlopen(main_link)

    # Reading the data from the main webpage 
    html = response.read().decode("utf-8")
    soup = bs4.BeautifulSoup(html, "html.parser")

    # Making sure the list(q_links) is empty 
    global q_links
    if q_links:
        q_links.clear()

    # We have to get the links to each quarter Page
    for match in soup.find_all("a"):
        q_links.append(f"http://mlg.ucd.ie/modules/python/sources/rental/{match.get('href')}")

    #print(q_links)

except urllib.error.HTTPError as e:
    print(f"HTTP Error {e.code}: Failed to retrieve {main_link}")
except urllib.error.URLError as e:
    print(f"Network Error: Failed to retrieve {main_link} - {e.reason}")
except Exception as e:
    print(f"Unexpected error retrieving {main_link}: {e}")

Cureently have 4 links each to the first page of each quarter
| Page| **Link** |
|:-----------:|:---------------:|
| Rentals: 2025 Q1 | [Q1-page01.html]("http://mlg.ucd.ie/modules/python/sources/rental/Q1-page01.html") |
| Rentals: 2025 Q2 | [Q2-page01.html]("http://mlg.ucd.ie/modules/python/sources/rental/Q2-page01.html") |
| Rentals: 2025 Q3 | [Q3-page01.html]("http://mlg.ucd.ie/modules/python/sources/rental/Q3-page01.html") |
| Rentals: 2025 Q4 | [Q4-page01.html]("http://mlg.ucd.ie/modules/python/sources/rental/Q4-page01.html") |

Working with Q1

I made a mistake with the links will have to come back

In [17]:
# """" Trying to create the database here starting with Q1 page one"""

# # Opening the link to the main webpage
# respons = urllib.request.urlopen(q_links[0])

# # Reading the data from the main webpage 
# html_content = respons.read().decode("utf-8")

# # We have to get the links to each quarter Page
# content = bs4.BeautifulSoup(html_content, "html.parser")

# full_data = content.find_all("li")

# # I am trying to get everything step by step now 
# for data in full_data:
#     # this gives me the month and the listing type daya before the rest in the table 
#     #data_type = data.find("span", {"class" : "record"}) 
#     # it give Jan 2025 but we know the year so i am taking just the month 
#     listing_month = data.find("span", {"class" : "record"}) .text.strip().split("—")[0].split(" ")[0]
#     # This gives me the type if it is a house or an apartment 
#     listing_type = data.find("span", {"class" : "record"}) .text.strip().split("—")[1].strip()

#     """ Now the tbody has all our data and I have realised that all the should i say keys are ina td tag but have a class of either v1 or v2 and the items are just in td tags no clas what so ever  in tags td
#     after each one with class there is one without class which is its value so i could hyst gice them different lists then iterate through, there is no  missing one i think"""
#     #data_keys =[data_key.text for data_key in data.find_all("td", {"class": ["v2", "v1"]}) ] 
#     # listing_keys = [data_key.text for data_key in data_keys] # listing keys 
#     data_items = [data_key.text for data_key in data.find_all("td",class_=lambda c: c is None) ] 
#     #print(data_items)
#     #listing_items = [data_item.text for data_item in data_items] # listing items 

#     """" now it is fair to say we can just we pair them, wait the keys ad the order is consistent throughtout so """
#     #Bedrooms must be a number, what if its not we will do that in error handling 
#     # We know that price is for a maonth and some still have per mon so we can do away with that and just keep the numbers as a float
#     # lets work on the price 
#     listing_price =  decimal.Decimal("".join(numerical for numerical in data_items[0] if numerical.isdigit() or numerical == ".")) # if its not working as wxpected i will change to float 
#     #print(listing_price)
#     # Working on the Location some have  "—" while others have "-" but what we realise is that it is either North or South then the actual location 
#     # I am think of splitingit so we know the ones in south and the ones in north, but all even in south and all odd is north so I think have the exact location is all we need then a way to get if it is even or odd
#     # with the location its not consistent some are D1 while others are Dublin 1 we want all in the full form so, we will work on that next 
#     listing_location = data_items[1].strip().replace("—", "-").replace("–","-").split("-")[1].strip()
#     if len(listing_location) < 6:
#         listing_location = listing_location.replace("D", "Dublin ")
#     #print(listing_location)

#     # Now I have to work on the Bedrooms they are showing as string and some have extract strings aside the number 
#     listing_bedrooms = int("".join(room for room in data_items[2] if room.strip().isdigit()))
#     #print(listing_bedrooms)

#     # Now I would have to do same for the bathrooms 
#     listing_bathrooms = int("".join(bath for bath in data_items[3] if bath.strip().isdigit()))

#     """ Parking for True: True/*true*, Yes/Y, 1 
#     False: False/*false*, No/N, 0, ot Available
#     Garden basically uses same just that it has an unknown"""
#     listing_yes = ["Yes", "Y", "True", "1", "yes"]
#     listing_no = ["No", "N", "False", "Not Available", "0", "no"]
#     listing_unknown = ["Unknkwn", "N/A", "???"] # this is just helping me now to know if there is more if not i will just take that out and then remire tye elif block for all the others 
#     if data_items[4].strip() in listing_yes:
#         listing_parking = "Yes"

#     elif data_items[4].strip() in listing_no:
#         listing_parking = "No"

#     else:
#         listing_parking = data_items[4].strip()

    
#     # For Garden 
#     if data_items[5].strip() in listing_yes:
#         listing_garden = "Yes"

#     elif data_items[5].strip() in listing_no:
#         listing_garden = "No"

#     elif data_items[5].strip() in listing_unknown:
#         listing_parking = "N/A"

#     else:
#         listing_parking = data_items[5].strip()


#     # Lease length is in months, some are empty so we have to do error handling here have to come back to this 
#     try: 
#         listing_lease = int("".join(lease for lease in data_items[6] if lease.strip().isdigit()))

#     except ValueError as e:
#         print(f"Lease length at {e}")
#         listing_lease = " "

#     if data_items[7].strip().lower() == "estate agent":
#         listing_contact = "Estate Agent"

#     elif data_items[7].strip().lower() == "owner":
#         listing_contact = "Owner"

#     else:
#         listing_contact = data_items[7].strip()



#     listing = {"Month": listing_month, "Type": listing_type, "Price": listing_price, "Location": listing_location, "Bedrooms": listing_bedrooms, "Bathrooms" : listing_bathrooms, "Parking": listing_parking, "Garden": listing_garden, "Lease Length": listing_lease, "Contact": listing_contact}

#     print(listing)
#     listings.append(listing)

# # print(type(listing["Bedrooms"]))
# #print(listings)
# # for lis in listings:
# #     if lis["Bedrooms"] > 2:
# #         print(lis)

# #print(int("".join(lease for lease in "  " if lease.strip().isdigit())))



# """" The not found page has the Text Not found in an h1 tag so we da that while the website hi tag text is not equation to found found"""

In [18]:
# # # Opening the link to the main webpage
# # respons = urllib.request.urlopen(q_links[0])

# # # Reading the data from the main webpage 
# # html_content = respons.read().decode("utf-8")
# import csv
# page_number = 1 
# finder = bs4.BeautifulSoup(urllib.request.urlopen(f"http://mlg.ucd.ie/modules/python/sources/rental/Q1-page{page_number:02}.html").read().decode("utf-8"), "html.parser")

# # We have to get the links to each quarter Page
# try: 
#     while(finder.find("h1").text != "Not Found"):
#         #print("Positive")
#         content = bs4.BeautifulSoup(urllib.request.urlopen(f"http://mlg.ucd.ie/modules/python/sources/rental/Q1-page{page_number:02}.html").read().decode("utf-8"), "html.parser")

#         full_data = content.find_all("li")

#         # I am trying to get everything step by step now 
#         for data in full_data:
#             # this gives me the month and the listing type daya before the rest in the table 
#             #data_type = data.find("span", {"class" : "record"}) 
#             # it give Jan 2025 but we know the year so i am taking just the month 
#             listing_month = data.find("span", {"class" : "record"}) .text.strip().split("—")[0].split(" ")[0]
#             # This gives me the type if it is a house or an apartment 
#             listing_type = data.find("span", {"class" : "record"}) .text.strip().split("—")[1].strip()

#             """ Now the tbody has all our data and I have realised that all the should i say keys are ina td tag but have a class of either v1 or v2 and the items are just in td tags no clas what so ever  in tags td
#             after each one with class there is one without class which is its value so i could hyst gice them different lists then iterate through, there is no  missing one i think"""
#             #data_keys =[data_key.text for data_key in data.find_all("td", {"class": ["v2", "v1"]}) ] 
#             # listing_keys = [data_key.text for data_key in data_keys] # listing keys 
#             data_items = [data_key.text for data_key in data.find_all("td",class_=lambda c: c is None) ] 
#             #print(data_items)
#             #listing_items = [data_item.text for data_item in data_items] # listing items 

#             """" now it is fair to say we can just we pair them, wait the keys ad the order is consistent throughtout so """
#             #Bedrooms must be a number, what if its not we will do that in error handling 
#             # We know that price is for a maonth and some still have per mon so we can do away with that and just keep the numbers as a float
#             # lets work on the price 
#             listing_price =  decimal.Decimal("".join(numerical for numerical in data_items[0] if numerical.isdigit() or numerical == ".")) # if its not working as wxpected i will change to float 
#             #print(listing_price)
#             # Working on the Location some have  "—" while others have "-" but what we realise is that it is either North or South then the actual location 
#             # I am think of splitingit so we know the ones in south and the ones in north, but all even in south and all odd is north so I think have the exact location is all we need then a way to get if it is even or odd
            
#             # with the location its not consistent some are D1 while others are Dublin 1 we want all in the full form so, we will work on that next 
#             # They all don't have the - some have just the main 
#             # try:
#             #     listing_location = data_items[1].strip().replace("—", "-").replace("–","-").split("-")[1].strip()
#             #     if len(listing_location) < 6:
#             #         listing_location = listing_location.replace("D", "Dublin ")

#             # except IndexError as e:
#             #     print(e)
#             # #print(listing_location)
#             full_address = data_items[1].strip().replace("—", "-").replace("–","-")
#             if "-" in full_address:
#                 listing_location = full_address.split("-")[0].strip()
#                 listing_postcode = full_address.split("-")[1].strip()
#                 if len(listing_postcode) < 6:
#                     listing_postcode = listing_postcode.replace("D", "Dublin ")

#             else:
#                 listing_location = full_address
#                 listing_postcode = ""
            

#             # Now I have to work on the Bedrooms they are showing as string and some have extract strings aside the number 
#             listing_bedrooms = int("".join(room for room in data_items[2] if room.strip().isdigit()))
#             #print(listing_bedrooms)

#             # Now I would have to do same for the bathrooms 
#             listing_bathrooms = int("".join(bath for bath in data_items[3] if bath.strip().isdigit()))

#             """ Parking for True: True/*true*, Yes/Y, 1 
#             False: False/*false*, No/N, 0, ot Available
#             Garden basically uses same just that it has an unknown"""
#             listing_yes = ["Yes", "Y", "True", "1", "yes"]
#             listing_no = ["No", "N", "False", "Not Available", "0", "no"]
#             listing_unknown = ["Unknown", "N/A", "???"] # this is just helping me now to know if there is more if not i will just take that out and then remire tye elif block for all the others 
#             if data_items[4].strip() in listing_yes:
#                 listing_parking = "Yes"

#             elif data_items[4].strip() in listing_no:
#                 listing_parking = "No"

#             else:
#                 listing_parking = "N/A"

            
#             # For Garden 
#             if data_items[5].strip() in listing_yes:
#                 listing_garden = "Yes"

#             elif data_items[5].strip() in listing_no:
#                 listing_garden = "No"

#             else:
#                 listing_garden = "N/A"


#             # Lease length is in months, some are empty so we have to do error handling here have to come back to this 
#             try: 
#                 listing_lease = int("".join(lease for lease in data_items[6] if lease.strip().isdigit()))

#             except ValueError as e:
#                 #print(f"Lease length at {e}")
#                 listing_lease = " "

            
#             listing_contact = data_items[7].strip().capitalize()



#             listing = {"Month": listing_month, "Type": listing_type, "Price": listing_price, "Location": listing_location, "Postcode": listing_postcode, "Bedrooms": listing_bedrooms, "Bathrooms" : listing_bathrooms, "Parking": listing_parking, "Garden": listing_garden, "Lease Length": listing_lease, "Contact": listing_contact}

#             #print(listing)
#             listings.append(listing)
#        # print(page_number)
#         page_number += 1


# except urllib.error.HTTPError as e:
#     print(f"HTTP Error {e.code}: Failed to retrieve 'http://mlg.ucd.ie/modules/python/sources/rental/Q1-page{page_number:02}.html'")
# except urllib.error.URLError as e:
#     print(f"Network Error: Failed to retrieve 'http://mlg.ucd.ie/modules/python/sources/rental/Q1-page{page_number:02}.html' - {e.reason}")
# except Exception as e:
#     print(f"Unexpected error retrieving 'http://mlg.ucd.ie/modules/python/sources/rental/Q1-page{page_number:02}.html': {e}")

# import csv
# print(len(listings))
# with open("trial.csv", "w", newline="") as csvfile:
#     writer = csv.DictWriter(csvfile, fieldnames=listings[0].keys())

#     writer.writeheader()

#     for row in listings:
#         writer.writerow(row)

#     csvfile.close()

Cureentlt have 4 links each to the first page of each quarter
| Page| **Link** |
|:-----------:|:---------------:|
| Rentals: 2025 Q1 | [Q1-page01.html]("http://mlg.ucd.ie/modules/python/sources/rental/Q1-page01.html") |
| Rentals: 2025 Q2 | [Q2-page01.html]("http://mlg.ucd.ie/modules/python/sources/rental/Q2-page01.html") |
| Rentals: 2025 Q3 | [Q3-page01.html]("http://mlg.ucd.ie/modules/python/sources/rental/Q3-page01.html") |
| Rentals: 2025 Q4 | [Q4-page01.html]("http://mlg.ucd.ie/modules/python/sources/rental/Q4-page01.html") |

Working with Q1

I made a mistake with the links will have to come back

In [19]:

#global listings
if listings:
    listings.clear()

for quarter_number, link in enumerate(q_links,1):
    page_number = 1
    # finder = bs4.BeautifulSoup(urllib.request.urlopen(f"http://mlg.ucd.ie/modules/python/sources/rental/Q{quarter_number}-page{page_number:02}.html").read().decode("utf-8"), "html.parser")
    
    while(True):
        try: 
         #finder.find("h1").text != "Not Found"
            #print("Positive")
            content = bs4.BeautifulSoup(urllib.request.urlopen(f"http://mlg.ucd.ie/modules/python/sources/rental/Q{quarter_number}-page{page_number:02}.html").read().decode("utf-8"), "html.parser")

            full_data = content.find_all("li")

            # I am trying to get everything step by step now 
            for data in full_data:
                # this gives me the month and the listing type daya before the rest in the table 
                #data_type = data.find("span", {"class" : "record"}) 
                # it give Jan 2025 but we know the year so i am taking just the month 
                listing_month = data.find("span", {"class" : "record"}).text.strip().split("—")[0].split(" ")[0]
                # This gives me the type if it is a house or an apartment 
                listing_type = data.find("span", {"class" : "record"}).text.strip().split("—")[1].strip()

                """ Now the tbody has all our data and I have realised that all the should i say keys are ina td tag but have a class of either v1 or v2 and the items are just in td tags no clas what so ever  in tags td
                after each one with class there is one without class which is its value so i could hyst gice them different lists then iterate through, there is no  missing one i think"""
                #data_keys =[data_key.text for data_key in data.find_all("td", {"class": ["v2", "v1"]}) ] 
                # listing_keys = [data_key.text for data_key in data_keys] # listing keys 
                data_items = [data_key.text for data_key in data.find_all("td",class_=lambda c: c is None) ] 
                #print(data_items)
                #listing_items = [data_item.text for data_item in data_items] # listing items 

                """" now it is fair to say we can just we pair them, wait the keys ad the order is consistent throughtout so """
                #Bedrooms must be a number, what if its not we will do that in error handling 
                # We know that price is for a maonth and some still have per mon so we can do away with that and just keep the numbers as a float
                # lets work on the price 
                listing_price =  float("".join(numerical for numerical in data_items[0] if numerical.isdigit() or numerical == ".")) # if its not working as wxpected i will change to float 
                #print(listing_price)
                # Working on the Location some have  "—" while others have "-" but what we realise is that it is either North or South then the actual location 
                # I am think of splitingit so we know the ones in south and the ones in north, but all even in south and all odd is north so I think have the exact location is all we need then a way to get if it is even or odd
                
                # with the location its not consistent some are D1 while others are Dublin 1 we want all in the full form so, we will work on that next 
                # They all don't have the - some have just the main 
                # try:
                #     listing_location = data_items[1].strip().replace("—", "-").replace("–","-").split("-")[1].strip()
                #     if len(listing_location) < 6:
                #         listing_location = listing_location.replace("D", "Dublin ")

                # except IndexError as e:
                #     print(e)
                # #print(listing_location)
                full_address = data_items[1].strip().replace("—", "-").replace("–","-")
                if "-" in full_address:
                    listing_location = full_address.split("-")[0].strip()
                    listing_postcode = full_address.split("-")[1].strip()
                    if len(listing_postcode) < 6:
                        listing_postcode = listing_postcode.replace("D", "Dublin ")

                else:
                    listing_location = full_address
                    listing_postcode = None
                

                # Now I have to work on the Bedrooms they are showing as string and some have extract strings aside the number 
                listing_bedrooms = int("".join(room for room in data_items[2] if room.strip().isdigit()))
                #print(listing_bedrooms)

                # Now I would have to do same for the bathrooms 
                listing_bathrooms = int("".join(bath for bath in data_items[3] if bath.strip().isdigit()))

                """ Parking for True: True/*true*, Yes/Y, 1 
                False: False/*false*, No/N, 0, ot Available
                Garden basically uses same just that it has an unknown"""
                listing_yes = ["Yes", "Y", "True", "1", "yes"]
                listing_no = ["No", "N", "False", "Not Available", "0", "no"]
                #listing_unknown = ["Unknown", "N/A", "???"] # this is just helping me now to know if there is more if not i will just take that out and then remire tye elif block for all the others 
                if data_items[4].strip() in listing_yes:
                    listing_parking = "Yes"

                elif data_items[4].strip() in listing_no:
                    listing_parking = "No"

                else:
                    listing_parking = None

                
                # For Garden 
                if data_items[5].strip() in listing_yes:
                    listing_garden = "Yes"

                elif data_items[5].strip() in listing_no:
                    listing_garden = "No"

                else:
                    listing_garden = None


                # Lease length is in months, some are empty so we have to do error handling here have to come back to this 
                try: 
                    listing_lease = int("".join(lease for lease in data_items[6] if lease.strip().isdigit()))

                except ValueError as e:
                    #print(f"Lease length at {e}")
                    listing_lease = None

                
                listing_contact = data_items[7].strip().title()


                listing = {"Month": listing_month, "Type": listing_type, "Price": listing_price, "Location": listing_location, "Postcode": listing_postcode, "Bedrooms": listing_bedrooms, "Bathrooms" : listing_bathrooms, "Parking": listing_parking, "Garden": listing_garden, "Lease Length": listing_lease, "Contact": listing_contact}

                #print(listing)
                listings.append(listing)
        # print(page_number)
            page_number += 1


        except urllib.error.HTTPError as e:
            print(f"HTTP Error {e.code}: Failed to retrieve 'http://mlg.ucd.ie/modules/python/sources/rental/Q{quarter_number}-page{page_number:02}.html'")
            break
        except urllib.error.URLError as e:
            print(f"Network Error: Failed to retrieve 'http://mlg.ucd.ie/modules/python/sources/rental/Q{quarter_number}-page{page_number:02}.html' - {e.reason}")
        except Exception as e:
            print(f"Unexpected error retrieving 'http://mlg.ucd.ie/modules/python/sources/rental/Q{quarter_number}-page{page_number:02}.html': {e}")

import csv
print(len(listings))
with open("trial.csv", "w", newline="") as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=listings[0].keys())

    writer.writeheader()

    for row in listings:
        #row["Price"] = format(row["Price"], ".2f")
        writer.writerow(row)

HTTP Error 404: Failed to retrieve 'http://mlg.ucd.ie/modules/python/sources/rental/Q1-page27.html'
HTTP Error 404: Failed to retrieve 'http://mlg.ucd.ie/modules/python/sources/rental/Q2-page26.html'
HTTP Error 404: Failed to retrieve 'http://mlg.ucd.ie/modules/python/sources/rental/Q3-page24.html'
HTTP Error 404: Failed to retrieve 'http://mlg.ucd.ie/modules/python/sources/rental/Q4-page24.html'
1900

In [20]:
import pandas as pd

In [21]:
df_data = pd.read_csv("trial.csv")
df_data

,Month,Type,Price,Location,Postcode,Bedrooms,Bathrooms,Parking,Garden,Lease Length,Contact
0,January,Apartment,840.0,Dublin City South,Dublin 12,1,2,Yes,No,12.0,Estate Agent
1,January,House,3110.0,Dublin City Nth.,Dublin 1,3,1,Yes,Yes,6.0,Owner
2,January,Apartment,2170.0,Dublin City South,Dublin 2,2,1,No,NaN,12.0,Estate Agent
3,January,House,2580.0,Dublin City Sth.,Dublin 6,3,2,Yes,Yes,12.0,Estate Agent
4,January,Apartment,1810.0,Dublin City North,Dublin 1,1,1,No,No,12.0,Estate Agent
...,...,...,...,...,...,...,...,...,...,...,...
1895,December,Apartment,1800.0,Dublin City Sth.,Dublin 2,1,2,NaN,No,12.0,Owner
1896,December,Apartment,2240.0,Dublin City Nth.,Dublin 1,1,1,No,No,12.0,Owner
1897,December,Apartment,2290.0,Dublin City South,Dublin 2,1,2,NaN,No,12.0,Owner
1898,December,House,2260.0,Dublin City North,Dublin 11,3,2,Yes,No,6.0,Estate Agent
1899,December,House,6410.0,Dublin City South,Dublin 6,5,2,No,Yes,3.0,Estate Agent

In [22]:
df_data["Contact"].unique()

<StringArray>
['Estate Agent', 'Owner', 'Estate  Agent']
Length: 3, dtype: str

In [23]:
df_data["Contact"] = df_data["Contact"].replace("Estate  Agent", "Estate Agent")
df_data["Contact"].unique()

<StringArray>
['Estate Agent', 'Owner']
Length: 2, dtype: str

In [24]:
df_data["Month"].unique()

<StringArray>
[  'January',  'February',     'March',     'April',       'May',      'June',
      'July',    'August', 'September',   'October',  'November',  'December']
Length: 12, dtype: str

In [25]:
df_data["Price"].dtypes

dtype('float64')

In [26]:
df_data["Lease Length"].dtypes

dtype('float64')

In [27]:
df_data["Bedrooms"].dtypes

dtype('int64')

In [28]:
df_data["Bathrooms"].dtypes

dtype('int64')

In [29]:
df_data["Garden"].dtype

In [30]:
df_data["Lease Length"] = df_data["Lease Length"].astype("Int64")

In [31]:
df_data["Lease Length"].dtypes

Int64Dtype()

In [32]:
df_data.describe

<bound method NDFrame.describe of          Month       Type   Price           Location   Postcode  Bedrooms  \
0      January  Apartment   840.0  Dublin City South  Dublin 12         1
1      January      House  3110.0   Dublin City Nth.   Dublin 1         3
2      January  Apartment  2170.0  Dublin City South   Dublin 2         2
3      January      House  2580.0   Dublin City Sth.   Dublin 6         3
4      January  Apartment  1810.0  Dublin City North   Dublin 1         1
...        ...        ...     ...                ...        ...       ...
1895  December  Apartment  1800.0   Dublin City Sth.   Dublin 2         1
1896  December  Apartment  2240.0   Dublin City Nth.   Dublin 1         1
1897  December  Apartment  2290.0  Dublin City South   Dublin 2         1
1898  December      House  2260.0  Dublin City North  Dublin 11         3
1899  December      House  6410.0  Dublin City South   Dublin 6         5

      Bathrooms Parking Garden  Lease Length       Contact
0             2     Yes     No            12  Estate Agent
1             1     Yes    Yes             6         Owner
2             1      No    NaN            12  Estate Agent
3             2     Yes    Yes            12  Estate Agent
4             1      No     No            12  Estate Agent
...         ...     ...    ...           ...           ...
1895          2     NaN     No            12         Owner
1896          1      No     No            12         Owner
1897          2     NaN     No            12         Owner
1898          2     Yes     No             6  Estate Agent
1899          2      No    Yes             3  Estate Agent

[1900 rows x 11 columns]>

In [33]:
df_data.info

<bound method DataFrame.info of          Month       Type   Price           Location   Postcode  Bedrooms  \
0      January  Apartment   840.0  Dublin City South  Dublin 12         1
1      January      House  3110.0   Dublin City Nth.   Dublin 1         3
2      January  Apartment  2170.0  Dublin City South   Dublin 2         2
3      January      House  2580.0   Dublin City Sth.   Dublin 6         3
4      January  Apartment  1810.0  Dublin City North   Dublin 1         1
...        ...        ...     ...                ...        ...       ...
1895  December  Apartment  1800.0   Dublin City Sth.   Dublin 2         1
1896  December  Apartment  2240.0   Dublin City Nth.   Dublin 1         1
1897  December  Apartment  2290.0  Dublin City South   Dublin 2         1
1898  December      House  2260.0  Dublin City North  Dublin 11         3
1899  December      House  6410.0  Dublin City South   Dublin 6         5

      Bathrooms Parking Garden  Lease Length       Contact
0             2     Yes     No            12  Estate Agent
1             1     Yes    Yes             6         Owner
2             1      No    NaN            12  Estate Agent
3             2     Yes    Yes            12  Estate Agent
4             1      No     No            12  Estate Agent
...         ...     ...    ...           ...           ...
1895          2     NaN     No            12         Owner
1896          1      No     No            12         Owner
1897          2     NaN     No            12         Owner
1898          2     Yes     No             6  Estate Agent
1899          2      No    Yes             3  Estate Agent

[1900 rows x 11 columns]>

In [34]:
df_data.head(10)

,Month,Type,Price,Location,Postcode,Bedrooms,Bathrooms,Parking,Garden,Lease Length,Contact
0,January,Apartment,840.0,Dublin City South,Dublin 12,1,2,Yes,No,12,Estate Agent
1,January,House,3110.0,Dublin City Nth.,Dublin 1,3,1,Yes,Yes,6,Owner
2,January,Apartment,2170.0,Dublin City South,Dublin 2,2,1,No,NaN,12,Estate Agent
3,January,House,2580.0,Dublin City Sth.,Dublin 6,3,2,Yes,Yes,12,Estate Agent
4,January,Apartment,1810.0,Dublin City North,Dublin 1,1,1,No,No,12,Estate Agent
5,January,Apartment,2830.0,Dublin City North,Dublin 1,2,2,No,No,12,Estate Agent
6,January,House,3520.0,Dublin City North,Dublin 1,4,2,No,Yes,3,Owner
7,January,Apartment,1650.0,Dublin City North,Dublin 1,1,1,No,No,12,Estate Agent
8,January,House,3280.0,Dublin City South,Dublin 22,3,2,Yes,Yes,12,Owner
9,January,Apartment,830.0,Dublin City South,Dublin 18,1,1,No,NaN,120,Estate Agent

In [35]:
df_data[df_data["Price"] > 2900.45]

,Month,Type,Price,Location,Postcode,Bedrooms,Bathrooms,Parking,Garden,Lease Length,Contact
1,January,House,3110.0,Dublin City Nth.,Dublin 1,3,1,Yes,Yes,6,Owner
6,January,House,3520.0,Dublin City North,Dublin 1,4,2,No,Yes,3,Owner
8,January,House,3280.0,Dublin City South,Dublin 22,3,2,Yes,Yes,12,Owner
10,January,Apartment,3030.0,Dublin City North,Dublin 1,2,1,Yes,No,12,Estate Agent
17,January,House,3880.0,Dublin City North,Dublin 7,5,1,Yes,Yes,12,Owner
...,...,...,...,...,...,...,...,...,...,...,...
1885,December,House,5000.0,Dublin City North,Dublin 1,4,2,Yes,Yes,120,Owner
1887,December,House,3340.0,Dublin City South,Dublin 12,4,1,No,Yes,6,Owner
1888,December,House,5920.0,Dublin City South,Dublin 8,3,2,Yes,NaN,3,Owner
1891,December,Apartment,3120.0,Dublin City South,Dublin 2,2,1,No,No,3,Estate Agent
1899,December,House,6410.0,Dublin City South,Dublin 6,5,2,No,Yes,3,Estate Agent

# Part Two

In [45]:
import pandas as pd

try:
    dataset = pd.read_csv("data.csv")

except FileExistsError as e:
    print(e)

dataset.isnull().sum()

Month             0
Type              0
Price             0
Location          0
Postcode        102
Bedrooms          0
Bathrooms         0
Parking         110
Garden          173
Lease Length     38
Contact           0
dtype: int64

In [47]:
dataset.head(10)

,Month,Type,Price,Location,Postcode,Bedrooms,Bathrooms,Parking,Garden,Lease Length,Contact
0,January,Apartment,840.0,Dublin City South,Dublin 12,1,2,Yes,No,12.0,Estate Agent
1,January,House,3110.0,Dublin City Nth.,Dublin 1,3,1,Yes,Yes,6.0,Owner
2,January,Apartment,2170.0,Dublin City South,Dublin 2,2,1,No,NaN,12.0,Estate Agent
3,January,House,2580.0,Dublin City Sth.,Dublin 6,3,2,Yes,Yes,12.0,Estate Agent
4,January,Apartment,1810.0,Dublin City North,Dublin 1,1,1,No,No,12.0,Estate Agent
5,January,Apartment,2830.0,Dublin City North,Dublin 1,2,2,No,No,12.0,Estate Agent
6,January,House,3520.0,Dublin City North,Dublin 1,4,2,No,Yes,3.0,Owner
7,January,Apartment,1650.0,Dublin City North,Dublin 1,1,1,No,No,12.0,Estate Agent
8,January,House,3280.0,Dublin City South,Dublin 22,3,2,Yes,Yes,12.0,Owner
9,January,Apartment,830.0,Dublin City South,Dublin 18,1,1,No,NaN,120.0,Estate Agent

In [48]:
dataset["Location"].unique()

<StringArray>
['Dublin City South',  'Dublin City Nth.',  'Dublin City Sth.',
 'Dublin City North',   'South Co Dublin',  'North  Co Dublin',
   'North Co Dublin',         'Nth. Co D',  'South  Co Dublin',
    'Nth. Co Dublin']
Length: 10, dtype: str

In [49]:
# tring to make the locations the same values so it is easier looking for items

universal_location = {"Dublin City Sth.": 'Dublin City South', 'Dublin City Nth.':'Dublin City North', 'Nth. Co D': 'North County Dublin', 'North  Co Dublin': 'North County Dublin', 'Nth. Co Dublin': 'North County Dublin','South  Co Dublin':'South County Dublin','North Co Dublin':  'North County Dublin', 'South Co Dublin': 'South County Dublin'} 
dataset["Location"] = dataset["Location"].replace(universal_location)
dataset["Location"].unique()

<StringArray>
[  'Dublin City South',   'Dublin City North', 'South County Dublin',
 'North County Dublin']
Length: 4, dtype: str

In [50]:
# Checking out contact 
dataset["Contact"].unique()

<StringArray>
['Estate Agent', 'Owner', 'Estate  Agent']
Length: 3, dtype: str

In [51]:
# making contact uniform 
universal_contact = {'Estate  Agent': 'Estate Agent'}
dataset["Contact"] = dataset["Contact"].replace(universal_contact)
dataset["Contact"].unique()

<StringArray>
['Estate Agent', 'Owner']
Length: 2, dtype: str

In [7]:
# working on Parking , has 110 missing 
dataset["Parking"].unique()

<StringArray>
['Yes', 'No', nan]
Length: 3, dtype: str

In [8]:
dataset["Parking"].mode()

0    No
Name: Parking, dtype: str

In [10]:
print(f"Parking No: {(dataset["Parking"] == 'No').sum()}")
print(f"Parking Yes: {(dataset["Parking"] == 'Yes').sum()}")

Parking No: 1224
Parking Yes: 566

In [ ]:
# let as group it to see if the price affects it having a parking or not, the tpe should definitely affect it 
dataset.groupby(["Location", "Parking","Type"])["Price"].agg(["count", "mean", "median", "min", "max"])

In [ ]:
dataset.groupby(["Location", "Type", "Bedrooms","Bathrooms", "Lease Length", "Parking"])["Price"].agg([ "median"]).unstack()

In [ ]:
# dataset[dataset["Parking"].isna()]

In [ ]:
parking_price = dataset.groupby(
    ["Location", "Type", "Bedrooms", "Parking"]
)["Price"].median().unstack()

parking_price

In [ ]:
parking_price["Difference"] = parking_price["Yes"] - parking_price["No"]
parking_price

In [ ]:
dataset.groupby(
    ["Location", "Type", "Bedrooms", "Parking"]
)["Price"].mean().unstack()

In [ ]:
# analysis = dataset.groupby(["Location","Type", "Parking", "Bedrooms", "Bathrooms"])["Price"].agg(["count", "mean", "median", "min","max"])

# analysis.head(50)

In [ ]:
dataset.groupby(["Location","Type", "Contact"])["Price"].agg(["count", "mean", "median"])

In [ ]:
dataset.groupby(["Type", "Contact","Parking"])["Price"].agg(["count", "mean", "median"])

In [ ]:

dataset.groupby(["Location","Type", "Contact","Parking", "Bedrooms"])["Price"].agg(["count", "mean", "median"])

In [ ]:
dataset.groupby(["Location","Type", "Contact","Parking", "Bedrooms", "Bathrooms"])["Price"].agg(["count", "mean", "median"])

In [ ]:
dataset.groupby(["Location","Type",  "Bedrooms", "Parking"])["Price"].agg(["mean", "median", "min","max"])

In [ ]:
# means = dataset.groupby(["Location", "Type", "Parking" ])["Price"].mean().unstack() # makes it a dataframe instead of a series 
# means["threshold"] = (means["No"] + means["Yes"]) / 2
# means

In [ ]:
# means.loc["Dublin City North", "threshold"]["Apartment"] # get series then the value
# means.loc[("Dublin City North", "Apartment"), "threshold"] # direct from dataframe

In [ ]:
# def filling_parking(row):
#     if pd.isna(row["Parking"]):
#         threshold = means.loc[(row["Location"], row["Type"]), "threshold"]
#         return "Yes" if row["Price"] > threshold else "No"
#     return row["Parking"]

# dataset["Parking"] = dataset.apply(filling_parking, axis= 1)
# dataset["Parking"].unique()

In [ ]:
#dataset.groupby(["Type","Location","Bedrooms", "Bathrooms"])["Parking"].value_counts(normalize=True).to_csv("haha.csv")

In [39]:
pd.crosstab(dataset["Type"], dataset["Parking"])

Parking      No  Yes
Type
Apartment  1097  258
House       127  308

In [100]:
pd.crosstab(dataset["Location"],dataset["Parking"], normalize="index")

Parking                    No       Yes
Location
Dublin City North    0.680641  0.319359
Dublin City South    0.697062  0.302938
North County Dublin  0.666667  0.333333
South County Dublin  0.705882  0.294118

In [ ]:
pd.crosstab(dataset["Postcode"], dataset["Parking"], normalize="index")

In [ ]:
# pd.crosstab(dataset["Type"], dataset["Price"], normalize="index")

In [ ]:
# pd.crosstab(dataset["Price"], dataset["Parking"], normalize="index")

In [ ]:
dataset.groupby(by= ["Type","Parking"])

In [ ]:
# working on Garden has 173 missing
dataset["Garden"].unique()

In [ ]:
# 402 Yes
(dataset["Garden"] == 'Yes').sum()

In [ ]:
# 1325 No
(dataset["Garden"] == 'No').sum()

In [ ]:
dataset[(dataset["Garden"] == 'Yes')]

In [ ]:
dataset[(dataset["Garden"] == 'Yes') & (dataset["Type"] == 'House')]
# all listinsg with Garden as houses 
# No apartment has a garden

In [57]:
#Since no apartment has a garden

dataset.loc[
    (dataset["Garden"].isna()) & (dataset["Type"] == "Apartment"),
    "Garden"
] = "No"

# dataset["Garden"] = dataset.loc[dataset["Type"] == "Apartment"]["Garden"].fillna("No"), makes all apartment no and house nan

In [ ]:
dataset.head(10)

In [ ]:
dataset["Garden"].isna().sum()

In [ ]:
dataset[dataset["Garden"].isna()]

In [ ]:
dataset.loc[(dataset["Type"]== "House") & (dataset["Garden"]== "Yes")]

In [ ]:
left = dataset.loc[(dataset["Type"]== "House") & (dataset["Garden"]== "No")]
left

In [ ]:
# pd.set_option("display.max_rows", None)
left.groupby(["Type", "Location", "Bedrooms", "Garden"])["Price"].agg(["mean", "median","min", "max"]).unstack()

In [ ]:
# From the data we see that all houses in North couty Dublin have a garden so it is fair to use that analogy for our data
dataset.loc[
    (dataset["Garden"].isna()) & (dataset["Location"] == "North County Dublin"), "Garden"] = "Yes"

dataset.groupby(["Type", "Location", "Garden"])["Price"].agg(["count", "mean", "median","min", "max"])

In [ ]:
dataset.groupby(["Type","Bedrooms"])["Garden"].value_counts(normalize=True)

In [ ]:
dataset.groupby(["Type","Bedrooms", "Bathrooms"])["Garden"].value_counts(normalize=True)

In [ ]:
dataset.groupby(["Type","Location","Bedrooms", "Bathrooms"])["Garden"].value_counts(normalize=True)

In [ ]:
# There is no clear relationship so we will assume all houses have gardens since the percentage of no is 9.026%
dataset.loc[(dataset["Garden"].isna()), "Garden"] = "Yes"
dataset.head(50)

In [70]:
dataset["Garden"].isna().sum()

np.int64(0)

In [ ]:
known = dataset[dataset["Parking"].notna()]
missing = dataset[dataset["Parking"].isna()]

y_train = known["Parking"]
x_train = pd.get_dummies(known[["Location", "Type","Bedrooms", "Bathrooms", "Price"]], prefix='', prefix_sep='', 
                   drop_first=True, dtype=int)

x_test = pd.get_dummies(
    missing[["Location","Type","Bedrooms","Bathrooms","Price"]],
    prefix='', prefix_sep='', drop_first=True, dtype=int
)

# x_test = x_test.reindex(columns=x_train.columns, fill_value=0)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(C=1e42, solver='liblinear')

model.fit(x_train,y_train)
y_predict = model.predict(x_test)
y_predict

ValueError: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- Location_Dublin City North
- Location_Dublin City South
- Location_North County Dublin
- Location_South County Dublin
- Type_Apartment
- ...

In [88]:
type(y_predict)
y_predict[0]

'No'

In [ ]:

parking_missing_indexes = list(dataset.loc[dataset["Parking"].isna()].index)
parking_missing_indexes

num = 0 
for index in parking_missing_indexes:
    dataset.loc[index , "Parking"] = y_predict[num]
    num += 1

Empty DataFrame
Columns: [Month, Type, Price, Location, Postcode, Bedrooms, Bathrooms, Parking, Garden, Lease Length, Contact]
Index: []

In [98]:
dataset["Parking"].isna().sum()

np.int64(0)

In [213]:
dataset["Type"].unique()
dataset["Month"].unique()

<StringArray>
[  'January',  'February',     'March',     'April',       'May',      'June',
      'July',    'August', 'September',   'October',  'November',  'December']
Length: 12, dtype: str

In [231]:
# Left with lease length
dataset.groupby(["Contact", "Type"])["Lease Length"].agg(["mean", "median","min", "max"]) # mode not build for agg
# dataset.groupby(["Contact","Type"])["Lease Length"].agg(["mean","median","min","max", lambda x: x.mode().iloc[0]])

                             mean  median  min    max
Contact      Type
Estate Agent Apartment  18.497175    12.0  3.0  120.0
             House      19.294355    12.0  3.0  120.0
Owner        Apartment  20.461538    12.0  3.0  120.0
             House      15.134328    12.0  3.0  120.0

In [232]:
dataset["Lease Length"].mode()

0    12.0
Name: Lease Length, dtype: float64

In [233]:
# Foe missing lease length we can say it is 12 because median is 12 across all and then the mode is also 12 
dataset["Lease Length"] = dataset["Lease Length"].fillna(12)
dataset["Lease Length"].isna().sum()

np.int64(0)

In [234]:
dataset["Postcode"].unique()

<StringArray>
['Dublin 12',  'Dublin 1',  'Dublin 2',  'Dublin 6', 'Dublin 22', 'Dublin 18',
 'Dublin 16', 'Dublin 13',  'Dublin 7', 'Dublin 20',  'Dublin 9', 'Dublin 15',
  'Dublin 4', 'Dublin 10', 'Dublin 11', 'Dublin 24',         nan,  'Dublin 3',
  'Dublin 8', 'Dublin 17', 'Dublin 14',  'Dublin 5', 'Dublin 6W']
Length: 23, dtype: str

In [263]:
missing_postcodes = dataset[dataset["Postcode"].isna()]
missing_postcodes.head(50)

,Month,Type,Price,Location,Postcode,Bedrooms,Bathrooms,Parking,Garden,Lease Length,Contact
43,January,Apartment,820.0,South County Dublin,NaN,1,2,No,No,12.0,Estate Agent
62,January,Apartment,3010.0,North County Dublin,NaN,3,2,No,No,12.0,Owner
71,January,Apartment,1220.0,South County Dublin,NaN,1,1,No,No,3.0,Estate Agent
73,January,Apartment,1840.0,South County Dublin,NaN,1,2,No,No,6.0,Estate Agent
75,January,Apartment,1750.0,North County Dublin,NaN,2,2,No,No,12.0,Estate Agent
111,January,Apartment,1520.0,North County Dublin,NaN,1,1,No,No,12.0,Estate Agent
126,January,Apartment,1640.0,North County Dublin,NaN,1,2,Yes,No,12.0,Estate Agent
140,January,House,2930.0,South County Dublin,NaN,4,3,Yes,Yes,12.0,Estate Agent
144,January,House,2490.0,North County Dublin,NaN,5,1,No,Yes,12.0,Estate Agent
151,January,House,4070.0,South County Dublin,NaN,4,4,Yes,Yes,3.0,Owner
162,January,Apartment,1660.0,South County Dublin,NaN,1,1,Yes,No,6.0,Owner
190,February,Apartment,1870.0,South County Dublin,NaN,1,1,No,No,60.0,Estate Agent
232,February,Apartment,1770.0,North County Dublin,NaN,2,2,No,No,12.0,Owner
238,February,House,4920.0,North County Dublin,NaN,4,2,Yes,Yes,3.0,Estate Agent
247,February,Apartment,2050.0,South County Dublin,NaN,1,2,No,No,12.0,Owner
257,February,Apartment,4260.0,South County Dublin,NaN,3,2,No,No,6.0,Estate Agent
259,February,House,3760.0,South County Dublin,NaN,4,1,Yes,Yes,120.0,Estate Agent
274,February,Apartment,1650.0,South County Dublin,NaN,1,1,No,No,12.0,Estate Agent
282,February,Apartment,2510.0,South County Dublin,NaN,2,2,No,No,120.0,Estate Agent
297,February,Apartment,750.0,North County Dublin,NaN,1,1,Yes,No,12.0,Estate Agent
392,March,House,3160.0,North County Dublin,NaN,4,1,No,Yes,6.0,Owner
409,March,Apartment,1780.0,North County Dublin,NaN,1,1,No,No,6.0,Estate Agent
411,March,House,4580.0,North County Dublin,NaN,3,1,Yes,Yes,6.0,Owner
439,March,House,2870.0,South County Dublin,NaN,3,1,No,Yes,12.0,Owner
445,March,House,3410.0,South County Dublin,NaN,3,2,Yes,Yes,12.0,Estate Agent
446,March,Apartment,1900.0,South County Dublin,NaN,1,1,No,No,12.0,Estate Agent
462,March,House,4260.0,North County Dublin,NaN,4,4,Yes,Yes,12.0,Estate Agent
469,March,Apartment,2160.0,South County Dublin,NaN,2,1,Yes,No,12.0,Estate Agent
485,March,Apartment,1400.0,South County Dublin,NaN,1,1,No,No,12.0,Estate Agent
520,April,House,3040.0,North County Dublin,NaN,4,2,Yes,Yes,12.0,Owner
529,April,Apartment,1400.0,South County Dublin,NaN,1,1,Yes,No,12.0,Estate Agent
589,April,House,3170.0,South County Dublin,NaN,3,2,Yes,Yes,6.0,Estate Agent
616,April,Apartment,2360.0,North County Dublin,NaN,3,1,No,No,12.0,Estate Agent
679,April,Apartment,1000.0,North County Dublin,NaN,1,2,Yes,No,12.0,Owner
715,May,Apartment,1820.0,South County Dublin,NaN,2,1,No,No,12.0,Owner
727,May,House,4080.0,South County Dublin,NaN,3,2,Yes,Yes,12.0,Estate Agent
748,May,Apartment,1140.0,South County Dublin,NaN,2,1,No,No,12.0,Estate Agent
761,May,House,5140.0,South County Dublin,NaN,3,2,No,Yes,6.0,Estate Agent
786,May,Apartment,1400.0,South County Dublin,NaN,1,2,No,No,12.0,Estate Agent
790,May,Apartment,940.0,North County Dublin,NaN,1,1,No,No,60.0,Owner
843,May,House,5330.0,South County Dublin,NaN,4,3,No,Yes,6.0,Owner
847,May,Apartment,1820.0,South County Dublin,NaN,1,2,No,No,12.0,Estate Agent
856,June,Apartment,1040.0,North County Dublin,NaN,1,1,No,No,12.0,Estate Agent
857,June,House,5070.0,South County Dublin,NaN,3,2,Yes,Yes,6.0,Estate Agent
858,June,Apartment,1860.0,South County Dublin,NaN,2,1,No,No,12.0,Estate Agent
892,June,House,4410.0,North County Dublin,NaN,3,2,Yes,Yes,12.0,Estate Agent
906,June,Apartment,1170.0,North County Dublin,NaN,1,1,No,No,30.0,Estate Agent
930,June,Apartment,2410.0,South County Dublin,NaN,2,1,No,No,12.0,Owner
933,June,Apartment,1560.0,North County Dublin,NaN,1,2,No,No,12.0,Estate Agent
937,June,House,4970.0,South County Dublin,NaN,3,2,No,Yes,6.0,Estate Agent

In [261]:
missing_postcodes["Location"].unique()

<StringArray>
['South County Dublin', 'North County Dublin']
Length: 2, dtype: str

In [262]:
dataset[dataset["Location"]== "North County Dublin"].shape[0]

51

In [ ]:
missing_postcodes[missing_postcodes["Location"]== "North County Dublin"].shape[0]
# we can say all the North county dublin locations do not have postcodes associated with them

51

In [255]:
dataset[dataset["Location"]== "South County Dublin"].shape[0]

51

In [ ]:
missing_postcodes[missing_postcodes["Location"]== "South County Dublin"].shape[0]
# we can say all the South county dublin locations do not have postcodes associated with them

51

In [282]:
missing_postcodes.reset_index(drop=True, inplace=True)
missing_postcodes

,Month,Type,Price,Location,Bedrooms,Bathrooms,Parking,Garden,Lease Length,Contact
0,January,Apartment,820.0,South County Dublin,1,2,No,No,12.0,Estate Agent
1,January,Apartment,3010.0,North County Dublin,3,2,No,No,12.0,Owner
2,January,Apartment,1220.0,South County Dublin,1,1,No,No,3.0,Estate Agent
3,January,Apartment,1840.0,South County Dublin,1,2,No,No,6.0,Estate Agent
4,January,Apartment,1750.0,North County Dublin,2,2,No,No,12.0,Estate Agent
...,...,...,...,...,...,...,...,...,...,...
97,December,Apartment,1210.0,North County Dublin,1,2,No,No,12.0,Estate Agent
98,December,House,4430.0,North County Dublin,3,2,Yes,Yes,30.0,Estate Agent
99,December,Apartment,1350.0,North County Dublin,2,1,No,No,12.0,Estate Agent
100,December,Apartment,2020.0,South County Dublin,1,1,No,No,12.0,Estate Agent
101,December,Apartment,1110.0,South County Dublin,1,2,No,No,12.0,Estate Agent

In [273]:

dataset.dropna(subset=["Postcode"], inplace=True)
dataset

,Month,Type,Price,Location,Postcode,Bedrooms,Bathrooms,Parking,Garden,Lease Length,Contact
0,January,Apartment,840.0,Dublin City South,Dublin 12,1,2,Yes,No,12.0,Estate Agent
1,January,House,3110.0,Dublin City North,Dublin 1,3,1,Yes,Yes,6.0,Owner
2,January,Apartment,2170.0,Dublin City South,Dublin 2,2,1,No,No,12.0,Estate Agent
3,January,House,2580.0,Dublin City South,Dublin 6,3,2,Yes,Yes,12.0,Estate Agent
4,January,Apartment,1810.0,Dublin City North,Dublin 1,1,1,No,No,12.0,Estate Agent
...,...,...,...,...,...,...,...,...,...,...,...
1895,December,Apartment,1800.0,Dublin City South,Dublin 2,1,2,No,No,12.0,Owner
1896,December,Apartment,2240.0,Dublin City North,Dublin 1,1,1,No,No,12.0,Owner
1897,December,Apartment,2290.0,Dublin City South,Dublin 2,1,2,Yes,No,12.0,Owner
1898,December,House,2260.0,Dublin City North,Dublin 11,3,2,Yes,No,6.0,Estate Agent
1899,December,House,6410.0,Dublin City South,Dublin 6,5,2,No,Yes,3.0,Estate Agent